### ISSUE TITLE
6lbr CoAP-DTLS on Sensortag CC2650

### ISSUE THREAD

**Issue by researchcom** [eclipse/tinydtls#102]
Hello

I am currently implementing the tinyDTLS in 6lbr with the Sensortag CC2650. Has anyone had success with doing this?

How to compiling and configuring tinyDTLS in 6lbr and Sensortag CC2650?

How to flash the tinyDTLS in Sensortag CC2650?

I am really confused about where to start.

Thank you!

**Comment by obgm** [comment]
I am not sure if this really is a tinydtls issue you are facing. It might be worth sending your question to the Contiki mailing list as well to try to get help with 6lbr. I suggest you start with the basic questions regarding 6lbr compilation and flashing the CC2650. Note that a proper 6lbr configuration already has support for tinydtls so this should not take any additional action. 
Be aware that according to the [specs](https://www.ti.com/product/CC2650) the CC2650 has 20 KiB of SRAM. In case the Sensortag does not additional RAM this might be a little tight for running 6lbr, so this might need some squeezing before you get it up and running.

**Comment by boaks** [comment]
Any additional help wanted?
Or can we close this issue?
