### ISSUE TITLE
DTLS server allows a handshake to be completed with invalid epochs

### ISSUE THREAD

**Issue by pfg666** [eclipse/tinydtls#13]
The dtls-server application will complete a handshake wherein the first two ClientHello carrying records sent by the client have epochs 1, while the rest have regular epochs (ClientKeyExchange and ChangeCipherSpec have epochs 0, Finished has epoch 1).

Attached at the end of the message is an archive containing a Wireshark capture of the invalid handshake. I am also posting an image of how this capture looks like, so that the interaction becomes clear.

Note that the server was configured to use the PSK password 1234 (you can input this in wireshark in order to decrypt the last finished messages).  
![bad_handshake](https://user-images.githubusercontent.com/2325013/60671833-4acf3800-9e74-11e9-8bcf-0d8ef22be8fd.png)

Cheers, Paul.

[bad_handshake.zip](https://github.com/eclipse/tinydtls/files/3359565/bad_handshake.zip)

**Comment by pfg666** [comment]
This problem (unlike the other one I posted) is present also in the develop branch. Basically, one can complete a first handshake in which the first two ClientHello messages have epochs 1 (while the rest of the messages have correct epochs).

**Comment by obgm** [comment]
Thank you for verifying this against develop.

**Comment by pfg666** [comment]
Hi! Could you confirm that this is a bug? I understand the severity might not be high enough to warrant a fix, however even confirmation would be useful in order to sell the technique we used to find it.

**Comment by sbernard31** [comment]
Except in case of renegociation ([which is not really recommended](https://tools.ietf.org/html/rfc7925#section-17)) , `CLIENT_HELLO` should always have an epoch = 0.

So my feeling is : this is a bug !

`CLIENT_HELLO` with epoch=1 MUST not be handled by the server. (except renegociation case and in this case the CLIENT_HELLO should be encrypted)
client MUST not start it's communication with epoch=1. It must start with epoch = 0 and only increment epoch after `CHANGE_CIPHER_SPEC`

**Comment by pfg666** [comment]
Thanks for the confirmation! I will keep this issue open then.

**Comment by boaks** [comment]
PR #89 has fixed this bug as well.

[dtls.c / stateless ClientHello processing](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4180-L4211)

If the ClientHello has a different epoch as 0, it must have an associated peer and the right encryption context including the MAC. A unencrypted epoch 1 message is with the PR generally dropped [dtls.c /  verify decrypt](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4243-L4296)

@pfg666 

If it's possible for you to spend the time to retest, please do so.
Otherwise, please close the issue.

**Comment by pfg666** [comment]
Appears to be fixed based on my tests. ClientHello with elevated epochs are correctly discarded.
