### ISSUE TITLE
Failed Assertion (dtls_send_client_key_exchange)

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#135]
### Description
- Type: Failing Assertion
- Priority: Medium
- The bug affects the develop branch 
---------------------------------------------------------------

**How to trigger** 
During a handshake, when a client expects a `server hello` message, if a maliciously crafted message with the handshake type `0x0c` (server key exchange) is sent to the client followed by a `server hello done`, the client first processes the message as a `server key exchange`. This successful processing of the `server key exchange` message [changes](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L3662) the state of the client to `DTLS_STATE_WAIT_SERVERHELLODONE`. Later, when the `server hello done` message is processed, the `dtls_send_client_key_exchange` function is [invoked](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L3354). In this step, based on the `handshake->cipher`, different functionalities are [activated](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L2610). Since the client and server did not agree on any cipher (no server hello is received by the client), the [assertion](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L2668) under the case `TLS_NULL_WITH_NULL_NULL` will be failed.

Take the following maliciously crafted message:

![Screen](https://user-images.githubusercontent.com/3464382/170208005-9f4a4004-e252-419c-a23f-b70605f0e5ac.png)

This message was originally a `server hello` message. We only changed the handshake type to `0x0c` (server key exchange). This modification will trigger the assertion.

I attached the maliciously crafted message in the following:
[malicious-message2.zip](https://github.com/eclipse/tinydtls/files/8768976/malicious-message2.zip)

**Comment by boaks** [comment]
I was able to reproduce it!

**Comment by boaks** [comment]
Please retest with PR #142

**Comment by bathooman** [comment]
Hello,

Thanks for the PR. Based on my tests, it indeed resolves the bug. So, I close this issue as there is a PR for it.
