### ISSUE TITLE
Out of bound pointer (dtls_handle_message)

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#136]
### Description
- Type: Out of bound pointer
- Priority: High
- The bug affects the develop branch
- This affects both the processing of the messages on the server-side and the client-side. However, for brevity, we only give an example of an attack scenario for a server.

---------------------------------------------------------------

**How to trigger** 
When the server is expecting a `change cipher spec` record during the handshake, if a maliciously crafted record with the content type `0x15` (Alert) is sent to the server, the server [identifies](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4415) it as an `Alert` record. the server then [processes](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4421) the record as an `Alert` and based on the [output value](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4422) of the `handle_alert` and the [type](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4423) of the `Alert`, shows a warning. Accessing the out-of-bound pointer occurs when the server accesses the [type](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4423) of the `Alert`.

Take the following maliciously crafted record:

![screentshot3](https://user-images.githubusercontent.com/3464382/170212467-228bc3a2-d0e3-4ba5-9220-83c8b5aa483d.png)

This record was originally a `change cipher spec` record. We only changed the content type to `0x15` (Alert). Notice that there is only one byte in the record (Length = 1). When this record is sent to the server, after the server processes it as an `Alert`, it attempts to identify the type of Alert by [accessing](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L4423) `data[1]` that is out-of-bound access.

I attached the maliciously crafted message in the following:
[malicious-message3.zip](https://github.com/eclipse/tinydtls/files/8769229/malicious-message3.zip)

**Comment by boaks** [comment]
Please retest with PR #141

**Comment by bathooman** [comment]
Hello,

Thanks for the PR. Based on my tests, it indeed resolves the bug. So, I close this issue as there is a PR for it.
