### ISSUE TITLE
Changing the development process, branch renaming

### ISSUE THREAD

**Issue by obgm** [eclipse/tinydtls#140]
@boaks has proposed a new development process which I support. The changes will include renaming the master branch to `main`.

* In the future, the branch `main` will contain contributions that have been reviewed by two different team members.
* Releases will be created from tagged versions in the `main` branch.
* The development branch will contain contributions in an early stage, possibly reviewed by only one team member.

[Renaming](https://github.com/github/renaming) the default branch will need a slight change on your local working copies as described [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes). You can do the change at your convenience as for the time being a redirect will be in place.

**Comment by obgm** [comment]
Update: 

- the [default branch now is `main`](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1357), and
- the `develop` HEAD has been [merged into `main`](https://github.com/eclipse/tinydtls/commit/4cd793be6ee594a9317de6a457d8b4d1ac85ebf4).

**Comment by mrdeep1** [comment]
Is it worth bumping the version at this point?

**Comment by obgm** [comment]
Yes, most likely. How about `1.0.0-rc1`?

**Comment by mrdeep1** [comment]
Works for me

**Comment by boaks** [comment]
Just to mention:
For "develop" I consider, that it will be "reset/force push" from time to time and/or the commits are edited to reflect additional commits from the "main".
For "main" the common grant (no force push, at least not without very good reason).

**Comment by obgm** [comment]
In most cases, there would be no need for doing a force push on the `develop` branch either as this is usually done in the PR's source branches only (and `--force-with-lease` usually removes most of the headache).
Unless the main branch is destroyed, a force push there should never ever be necessary.

**Comment by boaks** [comment]
I add some instructions to [CONTRIBUTING.md](CONTRIBUTING.md), see PR #151.

**Comment by boaks** [comment]
Done. Created issue #164 and pined that.
