### ISSUE TITLE
how to compile with the '-g' flag?

### ISSUE THREAD

**Issue by Spongman** [eclipse/tinydtls#144]
I have tried everything I can think of, but `configure` keeps stripping it out:

```
CFLAGS=-g ./configure -n --with-debug CFLAGS=-g 
```

**Comment by Spongman** [comment]
this seems backwards:
```
AC_ARG_WITH(debug,
  [AS_HELP_STRING([--without-debug],[disable all debug output and assertions])],
  [CPPFLAGS="${CPPFLAGS} -DNDEBUG -g"
   NDEBUG=1], 
  [])
```

**Comment by obgm** [comment]
Commit b9c58a1f accidentally broke the parameter passing into configure. Commit 98e2cd7 fixes this.

**Comment by boaks** [comment]
I test the new commit right now.

```
./configure --with-debug CFLAGS=-g 
```

works now.

@Spongman 

If possible, please retest and verify, that it "works for you".

**Comment by boaks** [comment]
@Spongman 

If you still have any issues, don't hesitate to comment on this issue again.
