### ISSUE TITLE
Delayed Completion of the Handshake

### ISSUE THREAD

**Issue by NErinola** [eclipse/tinydtls#191]
Our systematic analysis of DTLS implementations indicated that your DTLS stack contains one potential bug. We would be very happy if you would confirm this bug.

#### Tested build
Current "main" branch on GitHub

#### Observation 
We observed that TinyDTLS completed the handshake delayed when they received the ChangeCipherSpec and Finished messages out of order. In that event, they do not buffer out of order messages and wait for a retransmission from the client (see [tinydtls-e_reordering.pcapng](https://github.com/eclipse/tinydtls/files/10988379/tinydtls-e_reordering.zip)). This behavior can lead to a less efficient connection establishment when packets are received out of order due to the unreliable transport protocol. 

Best regards,
Nurullah Erinola

**Comment by boaks** [comment]
Just as remark:

the most DTLS implementations will put the CCS and Finish in one udp message, even if tinydtls doesn't do so (at least for now). With both in one udp message, reordering of CCS and Finish doesn't occur. Tinydtls keeps the handshake messages, but no appl. data message. But keeping appl. data messages requires then also to keep track of the used resources. So at that point, I don't consider to improve the implementation to deal with appl. data and Finish reordering.
