### ISSUE TITLE
Version Downgrade during the Handshake

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#209]
During our tests, we noticed that the handshake could continue if the server chooses to use a lower version of the protocol compared to the version used in earlier records through the handshake. I will try to clarify this through an example:

During the handshake, when the server sends the `ServerHello` message, it uses `DTLS 1.2` as the record version. Now if in the following record containing the `ServerHelloDone` message, the server chooses to use `DTLS 1.0` as the record version, the handshake continues without interruption. Although the security implications of this are unknown (or none in the case of TinyDTLS), I believe it is still good practice to abort when a version downgrade occurs. For example, OpenSSL aborts the handshake in such a scenario. An example of such a downgrade can be found in the attached PCAP file.

[tinydtls-0.zip](https://github.com/eclipse/tinydtls/files/12751220/tinydtls-0.zip)

**Comment by boaks** [comment]
Thanks for reporting. 
I will look into this tomorrow.

**Comment by boaks** [comment]
If possible, please test, if PR #210 works for you.

**Comment by boaks** [comment]
The fix is merged.
OK to close?

**Comment by bathooman** [comment]
Thanks for the fix.
