### ISSUE TITLE
tinydtls not compiling for Zephyr/Newlib

### ISSUE THREAD

**Issue by SebastianSchueller** [eclipse/tinydtls#225]
tinydtls doesn't build on Zephyr since 0e865aa, the `_GNU_SOURCE` causes conflicts in definitions present in toolchain/posix headers and in Zephyr headers.

Can be reproduced by trying to compile https://github.com/boaks/zephyr-coaps-client

**Comment by boaks** [comment]
Thanks for reporting. I'm on vacation and will have a look at it when I'm back next week.

**Comment by boaks** [comment]
Your PR #226  is available on branch "feature/connection_id" and "develop"
