### ISSUE TITLE
Renegotiation fails with test client/server application

### ISSUE THREAD

**Issue by pokgak** [eclipse/tinydtls#23]
Using the given `dtls-client` and `dtls-server` program in `tests/`, the server will fail when the client sends `client:renegotiate`.

Snippet from the *server* debug log ([full log](https://gist.github.com/pokgak/772520954c8873429a87507aedadb895)):

```
Dec 18 17:27:48 WARN decryption failed
Dec 18 17:27:48 INFO decrypt_verify() failed
```

After sending the command, the client also does not react anymore to new inputs from stdin.

**Comment by obgm** [comment]
Thank you very much. With your detailed information, reproducing the issue was easy.

**Comment by mrdeep1** [comment]
@pokgak This has been fixed in #41.  Please confirm that this fixes your issue.

**Comment by pokgak** [comment]
Confirmed #41 fixes this issue. Handshake completed successfully and no more error when running `client:renegotiate`.

**Comment by pokgak** [comment]
Closing because #41 is merged.
