### ISSUE TITLE
Outdated remark tindtls_decrypt on aliasing between src and buf

### ISSUE THREAD

**Issue by chrysn** [eclipse/tinydtls#24]
The docs of dtls_decrypt say that "Unlike dtls_encrypt(), the source and destination of dtls_decrypt() may overlap".

Given that dtls_encrypt doesn't say anything about that, and [the code](http://tinydtls.sourceforge.net/crypto_8h.html#a288c4ec1a5110ab3f44ab3cb7c289e69) contains explicit provisions for src=buf, that remark is likely to be outdated.

**Comment by obgm** [comment]
Thank you for spotting this. You are correct that this seems to be outdated. I will double-check and then fix the comment.

**Comment by boaks** [comment]
What I found in the documentation (branch develop):

[dtls_encrypt()](https://github.com/eclipse/tinydtls/blob/develop/crypto.h#L297)

> \p src and \p buf must not overlap.

So, based on the documentation, the statement in `dtls_decrypt()` isn't that bad.

Checking the implementation then shows:

[dtls_encrypt_params](https://github.com/eclipse/tinydtls/blob/develop/crypto.c#L587) 

```
if (src != buf)
    memmove(buf, src, length);
```

which, as stated in the issue, makes the documentation invalid.

I would go for removing the "overlap" statements and add documentation for `src` to `dtls_decrypt_params`.
I will go to prepare a PR for it.

**Comment by boaks** [comment]
Please check,  if PR #110 fixes this issue.

**Comment by boaks** [comment]
@chrysn 

if possible, please check, if the merged PR "works for you". If so, close this issue

**Comment by boaks** [comment]
@obgm 

I guess, this one can be closed.
