### ISSUE TITLE
Clarify const-ness of nonce and key in dtls_encrypt/_decrypt

### ISSUE THREAD

**Issue by chrysn** [eclipse/tinydtls#25]
In dtls_encrypt and dtls_decrypt, key and nonce are declared mutable (not const). That is unusual for AEAD operations as to my understanding.

Please consider clarifying this, descendingly preferably by
* making it const
* documenting that it's practically const (and save to cast to such) but not const for whichever reason, or
* documenting that (and why) key and nonce get changed.

**Comment by obgm** [comment]
Thank you for bringing this up. The parameters now have been made `const`, see d99fb8c.
