### ISSUE TITLE
PSK Authentication

### ISSUE THREAD

**Issue by simpyparveen** [eclipse/tinydtls#29]
The PSK authentication with ciphersuite TLS_PSK_WITH_AES_128_CCM_8, carries PSK ID:
memcpy(p, handshake->keyx.psk.identity, handshake->keyx.psk.id_length);
p += handshake->keyx.psk.id_length;

So does i mean it serves as client authentication ??  -- If server posses the psk mapped to that psk_id it goes on with handshake, if not reports error. 

Or is it server authentication by client which checks if server has the psk mapped to that psk_id, client can verify if the server is indeed in possession of psk mapped to the psk_id it sent, if and only if server sends a finished message, which client can authenticate correctly.

**Comment by obgm** [comment]
The psk_identity carries what could be seen as the "username" of the client (the psk_hint from the server side would identify the realm but is usually treated to be empty in IoT scenarios). To that extent, the combination of psk_identity and PSK serves as client authentication if the PSK is shared only between this client and the server. Furthermore, you could argue that the knowledge of the PSK on the server side also authenticates the server to the client. Of course, these authentication properties would rely on a strong (i.e., sufficiently random) PSK; the ciphersuite you mention unfortunately lacks a property that is called "forward-secrecy" and thus is useful for authentication purposes especially with short-lived PSKs.

**Comment by simpyparveen** [comment]
The is accurate explaination!
