### ISSUE TITLE
wrong value for prf_label_client?

### ISSUE THREAD

**Issue by zhenglining** [eclipse/tinydtls#36]
current version make prf_label_client = tinydtls, while californium makes it as "client", they can not work together.
and https://tools.ietf.org/html/rfc5246#section-7.4.9 tells it shoud be "client", why don't you follow them.

**Comment by obgm** [comment]
As far as I can see in the code, the finished label for calculating the verify_data is correctly set as "client finished". Can you please indicate where you think `prf_label_client` is set to anything but "client"?

And please: When you open an issue, please select a descriptive title from which one can tell what the question is about. The title you have chosen is too broad.

**Comment by zhenglining** [comment]
thanks,  I have
