### ISSUE TITLE
using libcoap with tinydtls - make uninstall fails

### ISSUE THREAD

**Issue by boaks** [eclipse/tinydtls#38]
> sudo make uninstall 
> Making uninstall in ext/tinydtls
> make[1]: Verzeichnis „..../libcoap/ext/tinydtls“ wird betreten
> make[1]: *** Keine Regel, um „uninstall“ zu erstellen.  Schluss.
> make[1]: Verzeichnis „..../libcoap/ext/tinydtls“ wird verlassen
> Makefile:1070: recipe for target 'uninstall-recursive' failed
> make: *** [uninstall-recursive] Error 1

Seems, that tinydtls provides "install", but has no target to "uninstall".

commit 7f8c86e in the tinydtls repository.

**Comment by obgm** [comment]
Sorry, I have messed up the PR, please ignore for now...

**Comment by boaks** [comment]
OK, ping me, if I can test it.
It's not that urgent, I can uninstall it manually.

**Comment by obgm** [comment]
Could you please check if commit 5cadc6e works properly? It is in branch uninstall-target which seems to have some weird commit history (strange enough: `git log --oneline --graph --decorate --all` shows it as being right on top of the develop HEAD).

**Comment by boaks** [comment]
Works for me.
