### ISSUE TITLE
There may be some null-dereference bugs in dtls.c

### ISSUE THREAD

**Issue by tluio** [eclipse/tinydtls#45]
In handle_handshake_msg(), the variable peer is checked in: 
   if (peer) {
       dtls_stop_retransmission(ctx, peer);
   }
This indicates that peer can be NULL.
If so, some null-dereference bugs will occur in handle_handshake_msg().
peer is also checked in line 3436:
   if (peer && !peer->handshake_params)
and it is dereferenced in line 3451:
   peer->state = DTLS_STATE_CLIENTHELLO;

**Comment by boaks** [comment]
On the server side, a `CLIENT_HELLO` is processed "stateless", so only for that case the `peer` may be NULL. With that, the `NULL` must be only considered processing such a `CLIENT_HELLO`. Maybe, moving the stateless part into a own function makes the code more readable and easier to ensure, that the `peer` is not NULL in the other cases. Or a check as:

```
  if (peer) {
    dtls_stop_retransmission(ctx, peer);
  } else if (data[0] != DTLS_HT_CLIENT_HELLO) {
        return dtls_alert_fatal_create(DTLS_ALERT_INTERNAL_ERROR);
  }
```

**Comment by boaks** [comment]
Fixed with PR #89

**Comment by boaks** [comment]
@obgm

That may be closed.

**Comment by obgm** [comment]
Thanks, closing.
