### ISSUE TITLE
HELLO_VERIFY_REQUEST - Protocol Version

### ISSUE THREAD

**Issue by boaks** [eclipse/tinydtls#46]
Adapting Eclipse Californium to my interpretation of [RFC 6347 - Section 4.2.1](https://tools.ietf.org/html/rfc6347#section-4.2.1) using 1.0 for the protocol version in the record header and in the server_version field of the hello_verify_request, that caused trouble with not compliant clients.

Investigating, it seems that RFC6347 is ambiguous about that. I wrote a e-mail to the IETF TLS mailing list, 
see [RFC 6347 - Section 4.2.1 - used version in a HelloVerifyRequest](https://mailarchive.ietf.org/arch/msg/tls/rQ3El3ROKTN0rpzhRpJCaKOrUyU/).

As far as I understand, tinydtls is using 1.0 for the record protocol version and 1.2 for the server_version in the hello_verify_request. There is a comment in dtls.c

> Signal DTLS version 1.0 in the record layer of ClientHello and
> HelloVerifyRequest handshake messages according to Section 4.2.1
> of RFC 6347.
> 
> This does not apply to a renegotation Client Hello

Are there any additional references about that?

Just to mention:
openssl: 1.0 for both
gnutls: 1.0 for both
mbedtls: 1.2 for both.

**Comment by mrdeep1** [comment]
> This does not apply to a renegotation Client Hello
> Are there any additional references about that?

Are you referring to the  renegotiation part (called rehandshake in RFC6347)  or the use of 1.2 in the server version in hello_verify_request?

RFC6347
````
   The HelloVerifyRequest message type is hello_verify_request(3).

   The server_version field has the same syntax as in TLS.  However, in
   order to avoid the requirement to do version negotiation in the
   initial handshake, DTLS 1.2 server implementations SHOULD use DTLS
   version 1.0 regardless of the version of TLS that is expected to be
   negotiated.
````
is only a SHOULD.  However, in tinyDTLS, the hello_verify_request has the version set to 1.0 (if you expand out the wireshark DTLSv1.2 record layer) - the server_hello has 1.2 - unless I am missing something.

I agree that mbedTLS is not playing by the 1.0 rules.

**Comment by mrdeep1** [comment]
> The server MUST use the same version number in the HelloVerifyRequest
> that it would use when sending a ServerHello. ...

OK - now see the conflict - I would have been expecting prior to this discussion the ServerHello to be 1.2, but HelloVerifyRequest to be 1.0.  I had just latched on the HelloVerifyRequest when I read your IETF TLS question.  It is unclear as to when 1.2 version negotiation should be taking place in the handshake.

**Comment by boaks** [comment]
Yep, so wait, if we get an answer.

**Comment by boaks** [comment]
I didn't receive an answer, but it seems to be also only a rare issue.
