### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by whitepoet** [eclipse/tinydtls#47]
when i make it in the tests, the error happen:/usr/bin/ld: cannot find -ltinydtls, my os is ubuntu 20.04
how can i solve it
thanks

**Comment by obgm** [comment]
It seems that you did not build libtinydtls first. Did you run `make` in the source tree's root directory?

**Comment by whitepoet** [comment]
> It seems that you did not build libtinydtls first. Did you run `make` in the source tree's root directory?

thanks. i got it
