### ISSUE TITLE
RFC7627 - client side only for ecdsa ?

### ISSUE THREAD

**Issue by boaks** [eclipse/tinydtls#50]
I currently implement the RFC7627/"extended master secret" for Eclipse/Californium.

First interoperability tests shows, that the tinydtls client of the "develop" branch uses the "extended_master_secret" only for rpk, not for psk. The tinydtls server responses to that extension for both rpk and psk.

Is this behavior, that the client only send "extended_master_secret" for rpk intended?

**Comment by mrdeep1** [comment]
It looks like this was an oversight and should be indicated as being supported in both psk and rpk.

**Comment by boaks** [comment]
Thanks!
