### ISSUE TITLE
Buffer Over-read Affecting check_server_hello() 

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#55]
Hello again,

The following over-read happens when you send a fragmented Server Hello message to the client. The bug is found employing symbolic execution technique. Suppose you have a `Server Hello` message with the following values for certain fields:

- `length` in the record layer = 46
- `length` in the handshake layer = 0
- `fragment length` = 128

When we are handling the message (in `dtls_handle_message()`), `data_length = decrypt_verify(peer, msg, rlen, &data)` is called. It returns a pointer to the first offset of the handshake layer (`uint8 *data`) and the real size of the handshake layer (`data_length` = 46). Later inside `check_server_hello(ctx, peer, data, data_length)`, Tiny tries to read different fields of the `Server Hello` message. It happens by advancing the pointer `data` and deducting the `data_length`. As I previously mentioned, the `Server Hello` is fragmented and it contains only up to the `random` field (`handshake header = 12` bytes + `handshake version = 2` bytes + `random = 32` bytes). Therefore, after advancing the pointer (`data`) for 46 bytes, Tiny tries to skip the `Session ID` by calling the [Macro](https://github.com/eclipse/tinydtls/blob/feature/handshake_fragmentation/dtls.c#L2765) (`SKIP_VAR_FIELD(data, data_length, uint8)`). However, Tiny already has advanced the pointer (`data`) for 46 bytes, and the pointer (`data`) is currently pointing to invalid memory. Therefore, here we have a one-byte over-read. I have added the assertion (`assert(data_length > 0)`) before `SKIP_VAR_FIELD(data, data_length, uint8)` to reveal the invalid read. For reproducing the bug, I have written a small UDP server that plays the role of a DTLS-server. 
I have attached the means to reproduce the mentioned bug. To do so, after downloading the suite, in tinydtls-witness/tests, execute the script `setupserver.sh` to compile TinyDTLS and `simple-udp-server`. Note that, I have de-randomized TinyDTLS for this demonstration and the patch is available in `tinydtls-witness/tests/patches`. Successful execution of `setupserver.sh` will run `simple-udp-server` on port 20220. Now, if you execute `reproduce.sh`, it will initiate a handshake with `simple-udp-server` and when it gets the Server Hello, the assertion that I added will fail.

![image](https://user-images.githubusercontent.com/3464382/111993050-739ad380-8b16-11eb-9daf-662ef4edb80c.png)

I hope I could explain it understandably. I appreciate the confirmation of the reported bugs.

Best,
Hooman Asadian
[tinydtls-witness.zip](https://github.com/eclipse/tinydtls/files/6182299/tinydtls-witness.zip)

**Comment by mrdeep1** [comment]
Thanks for the 2 issue reports you raised.  These are being looked into and will report back when analyzed.

**Comment by bathooman** [comment]
Dear @mrdeep1 

I also have checked this one. It affects all `master`, `develop` and `fragmentation-feature`.

**Comment by mrdeep1** [comment]
@bathooman Please check that #61 fixes your issue.

**Comment by bathooman** [comment]
Dear @mrdeep1,

To my best knowledge and based on my tests, the pull request successfully resolves the issue.

Regards,
Hooman

**Comment by boaks** [comment]
@bathooman 

Just to mention: though PR #61 is merged, and your issue is resolved with that, it's a common practice, that the one, who opened the issues, closes it as well. :-)

**Comment by bathooman** [comment]
This problem is already solved.
