### ISSUE TITLE
Over-read Affecting dtls_check_tls_extension()

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#69]
Hello,

In this case, the server sends a `server_hello` to the client where the `record_length` is smaller than the value it is supposed to be like the following (24 instead of 50):

![image](https://user-images.githubusercontent.com/3464382/115374314-00e04f00-a1cd-11eb-999d-2a1b26bed1a3.png)

Therefore, `data_length` will wrap-around [here](https://github.com/eclipse/tinydtls/blob/master/dtls.c#L2599) and later is used to read the `extensions` [here](https://github.com/eclipse/tinydtls/blob/master/dtls.c#L884) which causes the client to crash.

![image](https://user-images.githubusercontent.com/3464382/115375710-579a5880-a1ce-11eb-8165-eebf5f61ca35.png)

I have attached the means to reproduce the mentioned bug. To do so, after downloading the suite, in `tinydtls-develop/tests`, execute the script `setupserver.sh` to compile TinyDTLS and `simple-udp-server`. Note that, I have de-randomized TinyDTLS for this demonstration. Successful execution of `setupserver.sh` will run `simple-udp-server` on port 20220. Now, if you execute `reproduce.sh`, it will initiate a handshake with `simple-udp-server` and crashes the client.

[tinydtls-develop.zip](https://github.com/eclipse/tinydtls/files/6342519/tinydtls-develop.zip)

Best,
Hooman Asadian

**Comment by mrdeep1** [comment]
Fixed by merged PR #61.  Please confirm that it is no longer an issue.

**Comment by bathooman** [comment]
PR #61 solves this problem.
