### ISSUE TITLE
Buffer Over-read Affecting dtls_send_client_hello()

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#70]
Hi,

In this case, a `Hello_verify_request` contains a 16-byte cookie but the `cookie_length` is specified 32.

![image](https://user-images.githubusercontent.com/3464382/115378994-67676c00-a1d1-11eb-8eab-42636a00bd10.png)

When the `Hello_verify_request` is received, we use the `cookie_length` to read from the memory in [here](https://github.com/eclipse/tinydtls/blob/develop/dtls.c#L2631). It means we have a 16-byte memory over-read. I have attached the malformed `Hello_verify_request` for further investigations.

[HVR.zip](https://github.com/eclipse/tinydtls/files/6342691/HVR.zip)

Best,
Hooman Asadian

**Comment by mrdeep1** [comment]
@bathooman Please check if fix in PR #82 fixes this.

**Comment by bathooman** [comment]
This problem is already solved.
