### ISSUE TITLE
Message Sequence Non-conformance bug

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#72]
### Description
- Type: Non-conformance Bug
- Priority: Minor

---------------------------------------------------------------
## Non-conformance Bug
Version: development branch

**Expected behavior**   
The DTLS [RFC](https://www.rfc-editor.org/rfc/rfc6347.html#page-18) specifies the following requirement regarding the `message sequence number`:

> The first message each side transmits in each handshake always has message_seq = 0.  Whenever each new message is generated, the message_seq value is incremented by one.

**Actual behavior** 
One can complete a handshake with the following values for the message sequence:

CH0.sequence_number = 255
CH2.sequence_number = 191
CKE.sequence_number = 192
Finished.sequence_number = 193

The problem also exists when the server sends records with non-compliant sequence numbers. 

I have attached the handshake trace for the mentioned non-conformance. You clearly see that the handshake proceeds while the message_sequence is invalid.
[capture.zip](https://github.com/eclipse/tinydtls/files/6345519/capture.zip)

**Comment by mrdeep1** [comment]
I see the sequence number incrementing as expected, and then reset back to 0 when the Epoch goes from 0 to 1 in the packet capture.  What am I missing here from the packet capture?

**Comment by boaks** [comment]
This issue is about the [Handshake Message's message_seq](https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.2).

The issue about the [record's sequence_number](https://datatracker.ietf.org/doc/html/rfc6347#section-4.1)  is #71

It's not about, what tinydtls uses, it's about what tinydtls accepts.

**Comment by mrdeep1** [comment]
Oops - my bad.  I had keyed off text referring to CHx.sequence_number in the description rather than message_sequence.

**Comment by boaks** [comment]
:-) the last 5 years I'm frequently mixed up by that term-conflict.

**Comment by bathooman** [comment]
My bad. I should have used `*.message_seq` instead. :)

**Comment by boaks** [comment]
After checking the code, I re-analyzed this:

Though the initial "client_hello"s (unverified source address) are processed "state-less", no assumption could be made about their `message_seq`.

See [RFC6347,  4.2.1.  Denial-of-Service Countermeasures](https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.1)

> In order to counter both of these attacks, DTLS borrows the stateless
> cookie technique used by Photuris [PHOTURIS] and IKE [IKEv2].

If state would be used, that creates a vulnerability for massive spoofing client_hellos to exhaust the server resources keeping that state.

With that, the `message_seq` of CH0 and CH2 are not related for the server, and from CH2 on the `message_seq` are proper ordered. So my conclusion after this re-analysis:

No bug.

**Comment by boaks** [comment]
[RFC6347](https://datatracker.ietf.org/doc/html/rfc6347#page-19)

```
 Client                             Server
         ------                             ------
         ClientHello (seq=0)  ------>

                                 X<-- HelloVerifyRequest (seq=0)
                                                 (lost)

         [Timer Expires]

         ClientHello (seq=0)  ------>
         (retransmit)

                              <------ HelloVerifyRequest (seq=0)

         ClientHello (seq=1)  ------>
         (with cookie)

                              <------        ServerHello (seq=1)
                              <------        Certificate (seq=2)
                              <------    ServerHelloDone (seq=3)
```

while the first part (dropped messages and retransmission, isn't that relevant, the extract

```
         ClientHello (seq=0)  ------>

                              <------ HelloVerifyRequest (seq=0)

         ClientHello (seq=1)  ------>
         (with cookie)
```

shows the misery. The first CH with seq=0 must be processed stateless. The server doesn't track that. The second CD with seq=1 then shows, that when the server start to track this, the "seq" isn't longer 0.

With [RFC6347 4.2.1 end of section](https://datatracker.ietf.org/doc/html/rfc6347#page-18)

>    If a server receives a ClientHello with an invalid cookie, it SHOULD
>    treat it the same as a ClientHello with no cookie.  This avoids
>    race/deadlock conditions if the client somehow gets a bad cookie
>    (e.g., because the server changes its cookie signing key).
> 
>    Note to implementors: This may result in clients receiving multiple
>    HelloVerifyRequest messages with different cookies.  Clients SHOULD
>    handle this by sending a new ClientHello with a cookie in response to
>    the new HelloVerifyRequest.

It's also clear, that the CH seq may have a value larger than 1. Though the RFC doesn't define a limit for that, 191 will not be that probable, but is also not out of the scope of valid values. And, as already stated above, after CH2, everything works as expected.

So, even if RFC6347 mandates to start with seq 0, this can't be validated by the server. And so this case is no bug.

**Comment by bathooman** [comment]
With this description, it seems to me that we can close this issue. Thanks for the clarification. @boaks
