### ISSUE TITLE
Fragment Length, Fragment Offset Non-conformance bug

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#73]
### Description
- Type: Non-conformance Bug
- Priority: Minor

---------------------------------------------------------------
## Non-conformance Bug
Version: development branch

**Expected behavior**   
The DTLS [RFC](https://www.rfc-editor.org/rfc/rfc6347.html#section-4.2.3) specifies the following requirement regarding the `fragment offset` and `fragment length` when fragmentation is not present:

> An unfragmented message is a degenerate case with fragment_offset=0 and fragment_length=length

**Actual behavior** 
One can complete a handshake with the following values for the `fragment_offset` and `fragment_length`:

CKE.message_length = 17
CKE.fragment_length = 16777198
CKE.fragment_offset = 255

The problem also exists when the server sends records with non-compliant `Fragment_offset` and `fragment_length`. 

I have attached the handshake trace for the mentioned non-conformance. You clearly see that the handshake proceeds while the `Fragment_offset` and `fragment_length` are invalid.
[capture.zip](https://github.com/eclipse/tinydtls/files/6345693/capture.zip)

**Comment by mrdeep1** [comment]
Your code base is not the current develop branch as you indicate (fragment_offset is not used).  If #64 is merged into the develop branch, then the non-conformance you mention will get caught.  Even with #62 I am not sure where the non conformance is (24 bit masking) that allows the bad packet to get through..  The packet capture is telling me Fatal Alert: Handshake Failure has happened (sent back by the Server), but am unable to decrypt the encrypted handshakes.

**Comment by bathooman** [comment]
The problem is solved now. Thank you.
