### ISSUE TITLE
Cookie Exchange Bypass Bug

### ISSUE THREAD

**Issue by bathooman** [eclipse/tinydtls#74]
Hi,

This bug occurs when the server is unable to retrieve the cookie from a `ClientHello`.
Suppose that we send the following `ClientHello` to the server:

![image](https://user-images.githubusercontent.com/3464382/115719436-5eff6480-a37c-11eb-9f77-dfcbd5c0b34a.png)

As you can see, the Handshake version has an invalid value. This causes the server to fail to fetch the cookie [here](https://github.com/eclipse/tinydtls/blob/master/dtls.c#L1642). The problem is that the server returns the `err` [here](https://github.com/eclipse/tinydtls/blob/master/dtls.c#L1645) instead of the `len` and the value for `err` is zero (because of [here](https://github.com/eclipse/tinydtls/blob/master/dtls.c#L1633)). returning zero short circuits the cookie check and causes the server to proceed with the handshake by sending the `ServerHello` and `ServerHelloDone`. This makes TinyDTLS servers susceptible to Denial of Service attack.

I have attached the handshake trace in which we bypassed the cookie exchange mechanism by providing invalid values for the Handshake version.

[ch_inv_version.zip](https://github.com/eclipse/tinydtls/files/6358584/ch_inv_version.zip)

**Comment by mrdeep1** [comment]
Thank you for finding and reporting this bug.  See PR #77 for a fix.

**Comment by bathooman** [comment]
Great!
I am wondering why these PRs are not still merged in the Development branch. These are really severe issues that affect the codebase.

**Comment by mrdeep1** [comment]
@bathooman As PR #77 is now merged with develop, please confirm that this is working as expected and then close off this issue.

**Comment by bathooman** [comment]
It works as is expected. Feel free to close the issue.

Best

**Comment by obgm** [comment]
Great, thanks for the confirmation.
