### ISSUE TITLE
dtls_connect_peer() does not correspond to the API description

### ISSUE THREAD

**Issue by janosbrodbeck** [eclipse/tinydtls#75]
The description of `dtls_connect_peer()` states that it returns 0 when the channel already exists:
https://github.com/eclipse/tinydtls/blob/706888256c3e03d9fcf1ec37bb1dd6499213be3c/dtls.h#L269
But from looking at the code it does not. If the peer is found, `dtls_renegotiate()` is called which then tries to do a new handshake, but only when the session is established. So either the function would have to check if the connection exists and return 0, or the description doesn't fit, and it needs to be change that it does a re-connect in this case.
To change behavior the following lines instead of https://github.com/eclipse/tinydtls/blob/706888256c3e03d9fcf1ec37bb1dd6499213be3c/dtls.c#L4010 would fix that.
```
if (peer->state == DTLS_STATE_CONNECTED) {
      return 0;
}
```
Or am I misunderstanding something here?

**Comment by mrdeep1** [comment]
`dtls_connect() `expects a `0` return from `dtls_connect_peer()` to generate a renegotiation event.

PR #76 Updates the API documentation and creates a correct return following re-negotiate attempt in `dtls_connect_peer()`.

**Comment by mrdeep1** [comment]
@janosbrodbeck As #76 is now merged into develop can you please confirm this works as expected - if so, then please close off this issue.

**Comment by janosbrodbeck** [comment]
My finding has been resolved, thanks!
