### ISSUE TITLE
Infinite Loop Bug Affecting handling ClientHello Handkshake message 

### ISSUE THREAD

**Issue by jerrytesting** [eclipse/tinydtls#97]
Hello,

In the project master branch, an infinite loop bug had been found during handling ClientHello Handshake message. Suppose you have a malicious ClientHello message with the following values for the mentioned fields:
    1. **Cipher Suites Length** is an odd number like 3 (this is a malicious number)
    2. **Two Suites** whose length is 4 bytes
    3. **Extension Length** whose length is not zero like 26 bytes

After handling this message in the normal handling way as follows, we enter into the function **dtls_update_parameters()** at the dtls.c:980.
    1. 0x4e2b02 in dtls_update_parameters /home/etinydtls/dtls.c:1024:22
    2. 0x4e2b02 in handle_handshake_msg /home/etinydtls/dtls.c:3403:11
    3. 0x4cb1ce in handle_handshake /home/etinydtls/dtls.c:3493:14
    4. 0x4cb1ce in dtls_handle_message /home/etinydtls/dtls.c:3881:13
    5. 0x4c4efc in dtls_handle_read /home/etinydtls/tests/dtls-server.c:177:10
    6. 0x4c4efc in main /home/etinydtls/tests/dtls-server.c:352:2
    7. 0x7fb176ab10b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    8. 0x41c45d in _start (/home/etinydtls/tests/dtls-server+0x41c45d)

When coming to dtls.c:1005 in the function dtls_update_parameters(), variable **i** is assigned to a int number, which stands for all cipher suites' length 3 in this message. After that, the condition **data_length < i + sizeof(uint16)** cannot refuse this packet cannot exclude this packet, as 4+26 < 3+2 is no satisfied. Hence, we come to the loop of confirming suites at the dtls.c:1023, where **i** is decreased by 2 each loop. The ending loop condition includes (i == 0), while the initial value of i is 3 thereby this condition will not be satisfied. Unfortunately, one infinite loop incurs, which lets the server loop forever until consuming all resources. 

Here is a message packet to reproduce this bug: [https://github.com/jerrytesting/dtls-infiniteLoop.git]

I hope I could explain it clearly. Could you kindly have a check? Thanks a lot.

Kind Regards,
Jerry

**Comment by boaks** [comment]
```
 int i;
...
 i = dtls_uint16_to_int(data);
  if (data_length < i + sizeof(uint16)) {
    /* Looks like we do not have a cipher nor compression. This is ok
     * for renegotiation, but not for the initial handshake. */

    if (!security || security->cipher == TLS_NULL_WITH_NULL_NULL)
      goto error;

    config->cipher = security->cipher;
    config->compression = security->compression;

    return 0;
  }

  data += sizeof(uint16);
  data_length -= sizeof(uint16) + i;

  ok = 0;
  while ((i >= (int)sizeof(uint16)) && !ok) {
    config->cipher = dtls_uint16_to_int(data);
    ok = known_cipher(ctx, config->cipher, 0);
    i -= sizeof(uint16);
    data += sizeof(uint16);
  }

  /* skip remaining ciphers */
  data += i;
```
In "develop", I consider the loop is not infinite (at least, if `i` is signed).

**Comment by boaks** [comment]
Anyway, I think, a odd cipher suites length should fail deterministic.

**Comment by jerrytesting** [comment]
> Anyway, I think, a odd cipher suites length should fail deterministic.

**Comment by jerrytesting** [comment]
Agree with you. Thanks for your confirmation. 

In the master branch, this malformed packet brings infinite loops for DTLS servers. In the develop branch, the fixed also seems not correct, as lengths of cipher suits should be even numbers according to the DTLS RFC. So any packets with odd cipher lengths should be refused.

**Comment by boaks** [comment]
PR #101 got merged.

If possible, please retest with the fix.
otherwise please close this issue.
